title: Test Docs
description: Test Docs
remote_theme: carloseperate/jekyll-theme-rtd

# Theme settings:
site_author: Hong ZHANG
repo_url: "https://github.com/homehongzhang/testDocs"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
